# Generated by Django 3.1.5 on 2021-02-22 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImageConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='hero_images/', verbose_name='Картинка')),
                ('enabled', models.BooleanField(default=True)),
                ('hero_image_conf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.heroimageconf')),
            ],
        ),
    ]
