# Generated by Django 3.1.7 on 2021-02-27 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210227_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopHeroImageConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Набор верхних картинок слайдера',
                'verbose_name_plural': 'Наборы верхних картинок слайдера',
            },
        ),
        migrations.AlterModelOptions(
            name='heroimageconf',
            options={'verbose_name': 'Набор картинок слайдера', 'verbose_name_plural': 'Наборы картинок слайдера'},
        ),
        migrations.CreateModel(
            name='TopHeroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='top_hero_images/', verbose_name='Картинка')),
                ('enabled', models.BooleanField(default=True)),
                ('hero_image_conf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.topheroimageconf')),
            ],
        ),
    ]
