# Generated by Django 3.1.7 on 2021-02-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_translate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translate',
            options={'verbose_name': 'Translate', 'verbose_name_plural': 'Translate'},
        ),
        migrations.RenameField(
            model_name='topheroimage',
            old_name='title',
            new_name='title_am',
        ),
    ]
