# Generated by Django 3.1.7 on 2021-02-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210227_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topheroimage',
            old_name='content',
            new_name='content_am',
        ),
    ]
