# Generated by Django 3.1.7 on 2021-02-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210227_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='topheroimage',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='topheroimage',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='topheroimage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='topheroimage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (RU)'),
        ),
        migrations.AlterField(
            model_name='topheroimage',
            name='content_am',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (AM)'),
        ),
        migrations.AlterField(
            model_name='topheroimage',
            name='title_am',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (AM)'),
        ),
    ]
