# Generated by Django 3.1.7 on 2021-02-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210227_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_am', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (AM)')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (EN)')),
                ('content_am', models.TextField(blank=True, null=True, verbose_name='Описание (AM)')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='Описание (RU)')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Описание (EN)')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/', verbose_name='Картинка')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.service')),
            ],
        ),
    ]
