# Generated by Django 3.1.7 on 2021-02-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_service_serviceimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'verbose_name': 'Картинка сервиса', 'verbose_name_plural': 'Картинки сервиса'},
        ),
        migrations.AddField(
            model_name='translate',
            name='about2_am',
            field=models.CharField(max_length=255, null=True, verbose_name='О нас (2) (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='about2_en',
            field=models.CharField(max_length=255, null=True, verbose_name='О нас (2) (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='about2_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='О нас (2) (RU)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='about3_am',
            field=models.TextField(null=True, verbose_name='О нас (3) (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='about3_en',
            field=models.TextField(null=True, verbose_name='О нас (3) (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='about3_ru',
            field=models.TextField(null=True, verbose_name='О нас (3) (RU)'),
        ),
    ]
