# Generated by Django 3.1.7 on 2021-02-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210227_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='work_days1_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочие дни (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='work_days1_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочие дни (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='work_days1_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочие дни (RU)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='work_days2_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочие дни (2) (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='work_days2_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочие дни (2) (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='work_days2_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочие дни (2) (RU)'),
        ),
    ]
