# Generated by Django 3.1.7 on 2021-02-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210227_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='work_time_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочее время (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='work_time_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочее время (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='work_time_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочее время (RU)'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='work_days1_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочие дни (от - до) (AM)'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='work_days1_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочие дни (от - до) (EN)'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='work_days1_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочие дни (от - до) (RU)'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='work_days2_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочие дни (от - до) (2) (AM)'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='work_days2_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочие дни (от - до) (2) (EN)'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='work_days2_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Рабочие дни (от - до) (2) (RU)'),
        ),
    ]
