# Generated by Django 3.1.7 on 2021-02-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210227_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='contact_us_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Свяжитесь с нами (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='contact_us_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Свяжитесь с нами (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='contact_us_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Свяжитесь с нами (RU)'),
        ),
    ]
