# Generated by Django 3.1.7 on 2021-02-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210227_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='text_danger_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Электронная почта должна быть действительной, \n\n\t\t\tа длина сообщения должна превышать 1 символ (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='text_danger_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Электронная почта должна быть действительной, \n\n\t\t\tа длина сообщения должна превышать 1 символ (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='text_danger_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Электронная почта должна быть действительной, \n\n\t\t\tа длина сообщения должна превышать 1 символ (RU)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='text_success_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваше письмо отправлено (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='text_success_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваше письмо отправлено (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='text_success_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваше письмо отправлено (RU)'),
        ),
    ]
