# Generated by Django 3.1.7 on 2021-02-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210227_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='email_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Электронная почта (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='email_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Электронная почта (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='email_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Электронная почта (RU)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='name_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя и фамилия (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя и фамилия (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя и фамилия (RU)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='submit_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Отправить (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='submit_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Отправить (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='submit_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Отправить (RU)'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='text_danger_am',
            field=models.TextField(null=True, verbose_name='Электронная почта должна быть действительной, \n\n\t\t\tа длина сообщения должна превышать 1 символ (AM)'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='text_danger_en',
            field=models.TextField(null=True, verbose_name='Электронная почта должна быть действительной, \n\n\t\t\tа длина сообщения должна превышать 1 символ (EN)'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='text_danger_ru',
            field=models.TextField(null=True, verbose_name='Электронная почта должна быть действительной, \n\n\t\t\tа длина сообщения должна превышать 1 символ (RU)'),
        ),
    ]
