# Generated by Django 3.1.7 on 2021-02-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210227_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translate',
            options={'verbose_name': 'Перевод', 'verbose_name_plural': 'Перевод'},
        ),
        migrations.AddField(
            model_name='translate',
            name='sales_manager_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Менеджер продаж (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='sales_manager_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Менеджер продаж (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='sales_manager_name_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя менеджера продаж (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='sales_manager_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя менеджера продаж (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='sales_manager_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер менеджера продаж'),
        ),
        migrations.AddField(
            model_name='translate',
            name='sales_manager_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Менеджер продаж (RU)'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='text_danger_am',
            field=models.TextField(null=True, verbose_name='Электронная почта должна быть действительной,\n\t\t\tа длина сообщения должна превышать 1 символ (AM)'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='text_danger_en',
            field=models.TextField(null=True, verbose_name='Электронная почта должна быть действительной,\n\t\t\tа длина сообщения должна превышать 1 символ (EN)'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='text_danger_ru',
            field=models.TextField(null=True, verbose_name='Электронная почта должна быть действительной,\n\t\t\tа длина сообщения должна превышать 1 символ (RU)'),
        ),
    ]
