# Generated by Django 3.1.7 on 2021-02-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210227_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='director_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Директор (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='director_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Директор (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='director_name_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя директора (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='director_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя директора (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='director_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя директора (RU)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='director_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер директора'),
        ),
        migrations.AddField(
            model_name='translate',
            name='director_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Директор (RU)'),
        ),
    ]
