# Generated by Django 3.1.7 on 2021-02-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210227_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='ingenier_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Инженер (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='ingenier_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Инженер (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='ingenier_name_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя инженера (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='ingenier_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя инженера (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='ingenier_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя инженера (RU)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='ingenier_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер инженера'),
        ),
        migrations.AddField(
            model_name='translate',
            name='ingenier_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Инженер (RU)'),
        ),
    ]
