# Generated by Django 3.1.7 on 2021-02-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210227_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='finance_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Руководитель финансового отдела (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='finance_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Руководитель финансового отдела (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='finance_name_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя руководителя финансового отдела (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='finance_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя руководителя финансового отдела (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='finance_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя руководителя финансового отдела (RU)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='finance_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер руководителя финансового отдела'),
        ),
        migrations.AddField(
            model_name='translate',
            name='finance_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Руководитель финансового отдела (RU)'),
        ),
    ]
