# Generated by Django 3.1.7 on 2021-02-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210227_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='external_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Руководитель отдела внешних связей и департамента импорта (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='external_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Руководитель отдела внешних связей и департамента импорта (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='external_name_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя руководителя отдела внешних связей и департамента импорта (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='external_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя руководителя отдела внешних связей и департамента импорта (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='external_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя руководителя отдела внешних связей и департамента импорта (RU)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='external_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер руководителя отдела внешних связей и департамента импорта'),
        ),
        migrations.AddField(
            model_name='translate',
            name='external_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Руководитель отдела внешних связей и департамента импорта (RU)'),
        ),
    ]
