# Generated by Django 3.1.7 on 2021-02-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210227_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='address1_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес 1 (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='address1_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес 1 (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='address1_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес 1 (RU)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='address2_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес 2 (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='address2_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес 2 (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='address2_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес 2 (RU)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='address_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Слово адрес (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Слово адрес (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Слово адрес (RU)'),
        ),
    ]
