# Generated by Django 3.1.7 on 2021-02-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210227_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='number_row1',
            field=models.CharField(max_length=255, null=True, verbose_name='Строка номера 1'),
        ),
        migrations.AddField(
            model_name='translate',
            name='number_row2',
            field=models.CharField(max_length=255, null=True, verbose_name='Строка номера 2'),
        ),
    ]
