# Generated by Django 3.1.5 on 2021-02-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210227_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='message_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваше письмо (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='message_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваше письмо (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='message_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ваше письмо (RU)'),
        ),
    ]
