# Generated by Django 3.1.5 on 2021-03-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210307_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='partners_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Партнёры (AM)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='partners_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Партнёры (EN)'),
        ),
        migrations.AddField(
            model_name='translate',
            name='partners_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Партнёры (RU)'),
        ),
    ]
